### ISSUE TITLE
Explore the effects of filling in missing HDI data

### ISSUE THREAD

**Issue by tlofgren** [ds-proto/ds-proto.github.io#13]
If there are multiple countries missing HDI data, we may want to look at the effects of guessing the missing data. For instance, using the mean HDI of the geographic region for that country.

**Comment by tefu** [comment]
The file [HDR.xlsx](https://github.com/ds-proto/ds-proto.github.io/blob/master/data/HDR.xlsx) in the repo doesn't have many missing values, and cleaning them won't affect the final product _too_ much, so I'm marking this as closed for now.
